Sprint 11
flukekoh/ImageFeed pull request #3
Opened 2023-01-28 12:07 UTC by flukekoh

2023-01-28 18:07 UTC, tsaidov7 commented on ImageFeed/AlertPresenter.swift
> +import UIKit
Не нужно импортить оба фреймворка: UIKit содержит в себе Foundation

2023-01-28 18:11 UTC, tsaidov7 commented on ImageFeed/OAuth2/OAuth2Service.swift
> +            }
Ой-ей-ей) Не совсем красивая конструкция)
```
guard task == nil else {
   if lasCode != code {
       task?.cancel()
   }
   return
}
```

2023-01-28 18:17 UTC, tsaidov7 commented on ImageFeed/OAuth2/OAuth2Service.swift
> +//        }
Давай комментарии удалять перед сдачей спринта, потому что он мешает проверяющим?

2023-01-28 18:19 UTC, tsaidov7 commented on ImageFeed/OAuth2/OAuth2Service.swift
> +                    completion(.success(result.accessToken))
Так операции уже на главном потоке ведь... Сессия же в методе objectTask при успехе переводит задачи на главный поток и вызывает комплишн

2023-01-28 18:19 UTC, tsaidov7 commented on ImageFeed/ObjectTask.swift
> +                    completion(.failure(error))
Все комплишены, как при успехе, так и при ошибках, надо переводить на главную очередь

2023-01-28 18:20 UTC, tsaidov7 commented on ImageFeed/ObjectTask.swift
> +            }
А если бинарных данных нет? Может, обработать эту ошибку?

2023-01-28 18:20 UTC, tsaidov7 commented on ImageFeed/ProfileImageService.swift
> +    static let DidChangeNotification = Notification.Name(rawValue: "ProfileImageProviderDidChange")
С маленькой буквы)
С заглавной буквы объявляются только типы данных

2023-01-28 18:21 UTC, tsaidov7 commented on ImageFeed/ProfileImageService.swift
> +    static let shared = ProfileImageService()
Если это синглтон, то еще хорошо бы добавить конструктор
`private init() {}`

2023-01-28 18:21 UTC, tsaidov7 commented on ImageFeed/ProfileImageService.swift
> +        lastUsername = username
Тоже давай переделаем. Вместо вложенных if используем guard

2023-01-28 18:24 UTC, tsaidov7 commented on ImageFeed/ProfileImageService.swift
> +                self?.lastUsername = ""                     // 16
Ну тоже, хорошо бы переводить комплишены на главную очередь

2023-01-28 18:30 UTC, tsaidov7 commented on ImageFeed/ProfileService.swift
> +        let task = session.objectTask(for: request) { [weak self] (result: Result<ProfileResult, Error>) in
Смотри, каждый сервис делает запросы... И ты копипастишь по сути один и тот же код. Это нарушение принципа DRY - Don't Repeat Yourself
Советую выделить отдельный объект, закрытый протоколом NetworkRouter
`final class NetworkRouterImp: NetworkRouter`
Он будет иметь один метод
`func request<T: Decodable>(_ endPoint: URL, type: T.Type, completion: @escaping (Result<T, Error>) -> Void)`
Ну а реализация простая
- делаешь запрос с помощью таски сессии URLSession.shared.dataTask
- парсишь ответ в T c помощью JSONDecoder объекта
- передаешь ответ в виде комплишена наверх

2023-01-28 18:33 UTC, tsaidov7 commented on ImageFeed/ProfileService.swift
> +        let task = session.objectTask(for: request) { [weak self] (result: Result<ProfileResult, Error>) in
Сервисы при этом отдают ответственность за создание таски, взаимодействие с сервером и парсинг ответов этому роутеру
```
final class MyService {

   private let networkRouter: NetworkRouter = NetworkRouterImp.shared // Можно синглтон

   func fetchData(completion: ...) {
      self.networkRouter.request(...) {
         switch result {
         ...

```

2023-01-28 18:36 UTC, tsaidov7 commented on ImageFeed/SplashViewController.swift
>                  self.switchToTabBarController()
Рановато открываешь таб бар
Еще не получил профиль, аватарку, а уже показываешь основной экран
Если получишь ошибку от профиля, то будет краш

2023-01-28 18:38 UTC, tsaidov7 commented on ImageFeed/SplashViewController.swift
> +                //                self.switchToTabBarController()
Логичнее подменять рутовый контроллер окна именно тут

2023-01-28 18:42 UTC, tsaidov7 commented on ImageFeed/AppDelegate.swift
> +        return sceneConfiguration
Черный экран при старте...
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/37248555/215285203-ed783d45-a4e6-4cdf-98fb-5c2c9b847549.png">

2023-01-28 18:43 UTC, tsaidov7 commented on ImageFeed/AppDelegate.swift
> +        return sceneConfiguration
Куда экран аутентификации-то презентится?
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/37248555/215285264-1f70cc1a-983a-4f77-b1c5-a1b15f2c0204.png">

2023-01-28 18:45 UTC, tsaidov7 commented on ImageFeed/AppDelegate.swift
> +        return sceneConfiguration
Ошибка тут
Почему контроллер программно создается? Он же реализован в IB... Загружать его надо через сториборд
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/37248555/215285333-dcd633e5-af0a-4e8c-92a1-933cb1b9187f.png">

2023-01-29 08:54 UTC, flukekoh commented on ImageFeed/ProfileService.swift
> +        let task = session.objectTask(for: request) { [weak self] (result: Result<ProfileResult, Error>) in
не понял как это сделать верно. реквесты отличаются, комплименты разные и сделан objectTask. я не понял что кроме urlsession и вызова таска я могу перенести в network router. Остальные пункты поправил

2023-01-29 21:48 UTC, tsaidov7 commented on ImageFeed.xcodeproj/project.pbxproj
> +		A208E90F29865824001F5D0F /* NetworkRouter.swift in Sources */ = {isa = PBXBuildFile; fileRef = A208E90E29865824001F5D0F /* NetworkRouter.swift */; };
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/37248555/215357465-f0dc2fce-af9e-45c6-9ba1-bdfca237c08e.png">
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/37248555/215357444-bc784372-9a53-4d05-96ce-e9bf17f66492.png">

2023-01-30 08:59 UTC, flukekoh commented on ImageFeed.xcodeproj/project.pbxproj
> +		A208E90F29865824001F5D0F /* NetworkRouter.swift in Sources */ = {isa = PBXBuildFile; fileRef = A208E90E29865824001F5D0F /* NetworkRouter.swift */; };
@tsaidov7 Я не знал что если не положить все файлы в гит то он не соберется. Я не стал класть файл с неудачной попыткой NetworkRouter и оно легло((

2023-01-31 15:11 UTC, IBDesignable requested changes
Не готова принять работу, есть ошибки, блокирующие работу приложения. Нужно отладить. 

Также требуется не только устранить ошибки, но и почистить код. Среди загородей комментариев – ничего уже не разобрать.

2023-01-31 15:11 UTC, IBDesignable commented on ImageFeed/Auth/WebViewViewController.swift
> +//        updateProgress()
было правильно сделано: регистрация на дид апиар, удаление обсервера на диддисапир. Не знаю что привело к новым изменениям в этом файле

2023-01-31 15:11 UTC, IBDesignable commented on ImageFeed/Auth/AuthViewController.swift
>  final class AuthViewController: UIViewController {
В этом классе перед тем как делегировать код дальше по иерархии, забыт dismiss webview. 
Одна из причин, почему UI экрана дальше может блокироваться. 

Давай допишем:
```
dismiss(animated: true) { [weak self] in
    guard let self = self else { return }
    self.delegate?.authViewController(self, didAuthenticateWithCode: code)
}
```

пс: не могу оставить комментарий к нужной строчке в классе

2023-01-31 15:11 UTC, IBDesignable commented on ImageFeed/OAuth2/OAuth2Service.swift
> +                self?.lastCode = nil
в случае ошибки тоже надо обнулить таску. Давай вынесем за скобки result'а 

self?.task = nil

2023-01-31 15:11 UTC, IBDesignable commented on ImageFeed/OAuth2/OAuth2TokenStorage.swift
> +            guard let newValue = newValue else {return}
для nil-кейса лучше сделать removeObject(key ) чтобы убрать из хранилища значение

Это тебе поможет отлаживать авторизацию.

2023-01-31 15:11 UTC, IBDesignable commented on ImageFeed/SplashViewController.swift
> +            UIBlockingProgressHUD.show()
Сейчас после авторизации происходит не понятный мне баг: ui блочится. 
В текущей реализации очень много закоментированного кода, лишних операций, не конконтролируемых вызовов не на UI-потоке. Что усложняет дебагинг и поиск ошибки во флоу. 
Задачу надо почистить от мусора, лучше начать с нуля. И аккуратно восстанавливать по шагам что и зачем должно вызываться. 

Начнем отсюда: 

зачем-то два раза показываешь  UIBlockingProgressHUD.show(). Это не ок.

Предлагаю явно вызвать  
1) dismiss(animated: true) на  vc AuthViewController. 
2) Затем вызвать фетч токена. 
3) При разборе результата фетча – после switch result снять блокировку UIBlockingProgressHUD.dismiss(). 

На успешном кейсе должен вызваться fetchProfile, с ним точно также блокировку UI, затем блокировку снять после свитча. 

--- 

Я заметила, что ты фетчишь токен во viewDidAppear, что кажется логичным. Однако почему-то этот метод пытается сработать второй раз, когда ты меняешь вью контроллер на таббар. 

Поэтому я предлагаю в этой задаче отказаться от этого решения, и сделать это в viewDidLoad самой последним вызовом.  

--- 

Про DispatchQueue.main.async. 
Неплохим решением могло бы быть оборачинвание в комплишен в ObjectTask. Однако это смешение двух разных слоев – сетевого слоя, и слоя презентации. 
В данной ситуации, я рекомендую также аккуратно обернуть все замыкания в UI на главную очередь – это позволит явно видеть, что UI в данный момент меняется именно с главной очереди. 
После отладки проблем, можно будет вернуть назад.

2023-01-31 15:11 UTC, IBDesignable commented on ImageFeed/ProfileImageService.swift
> +                }
тут хорошо, что комплишены на главной очереди, однако как я поняла, objectTask уже возвращает на главной. И теперь это излишне. 

Повторю, свой комментарий выше: лучше оборачивать на главную очередь рядом c UI кодом. 
Так и чтение упростится, и лишний раз беспокоиться не надо будет, что где-то мог забыть это сделать.

2023-01-31 15:11 UTC, IBDesignable commented on ImageFeed/ProfileImageService.swift
> +                    self.task = nil
тоже самое надо вызвать и для failure кейса. А лучше написать один раз, за рамками switch

2023-01-31 15:11 UTC, IBDesignable commented on ImageFeed/ProfileService.swift
> +        }
хорошо бы возвращать ошибку, если делаешь выход из функции. Иначе в местах где ты вызываешь этот код, вероятно может заблокироваться UI за счет алертов.

2023-01-31 15:11 UTC, IBDesignable commented on ImageFeed/ProfileService.swift
> +        let task = session.objectTask(for: request) { [weak self] (result: Result<ProfileResult, Error>) in
Не рекомендую углубляться сейчас в обобщенное программирование, реализацию подобного сервиса можно оставить на потом.

2023-01-31 15:11 UTC, IBDesignable commented on ImageFeed/ProfileService.swift
> +                    self.task = nil
и здесь, таску обнулить для второго случая тоже. Аналогично комментариям выше

2023-02-02 06:34 UTC, flukekoh commented on ImageFeed/Auth/WebViewViewController.swift
> +//        updateProgress()
Исправил. Вернул как было

2023-02-02 06:38 UTC, flukekoh commented on ImageFeed/Auth/AuthViewController.swift
>  final class AuthViewController: UIViewController {
Добавил

2023-02-02 06:39 UTC, flukekoh commented on ImageFeed/OAuth2/OAuth2Service.swift
> +                self?.lastCode = nil
Исправил

2023-02-02 06:40 UTC, flukekoh commented on ImageFeed/OAuth2/OAuth2TokenStorage.swift
> +            guard let newValue = newValue else {return}
Поправил

2023-02-02 06:42 UTC, flukekoh commented on ImageFeed/ProfileImageService.swift
> +                    self.task = nil
Исправил

2023-02-02 06:45 UTC, flukekoh commented on ImageFeed/ProfileService.swift
> +        }
@IBDesignable не очень понял зачем возвращать ошибку. Мы же, как я понимаю, просто не хотим чтоб функция шла дальше если у нас уже есть необработанный запрос. Мы хотим просто выйти из функции

2023-02-02 06:55 UTC, flukekoh commented on ImageFeed/ProfileService.swift
> +                    self.task = nil
Исправил

2023-02-02 07:02 UTC, flukekoh commented on ImageFeed/ProfileImageService.swift
> +                }
Исправил

2023-02-02 07:32 UTC, flukekoh commented on ImageFeed/SplashViewController.swift
> +            UIBlockingProgressHUD.show()
> Задачу надо почистить от мусора

Убрал лишнее во всех модулях

> зачем-то два раза показываешь UIBlockingProgressHUD.show(). Это не ок.

Исправил

> Предлагаю явно вызвать
dismiss(animated: true) на vc AuthViewController.
Затем вызвать фетч токена.
При разборе результата фетча – после switch result снять блокировку UIBlockingProgressHUD.dismiss().
На успешном кейсе должен вызваться fetchProfile, с ним точно также блокировку UI, затем блокировку снять после свитча.

Исправил, проверил. Блокировки нет. Количество show dismiss для HUD совпадает

> Я заметила, что ты фетчишь токен во viewDidAppear, что кажется логичным. Однако почему-то этот метод пытается сработать второй раз, когда ты меняешь вью контроллер на таббар.
Поэтому я предлагаю в этой задаче отказаться от этого решения, и сделать это в viewDidLoad самой последним вызовом.

Переделал. 

Проверил авторизацию и запуск с уже авторизованным пользователем. Блокировки UI нет

2023-02-02 19:30 UTC, ABashkirova reviewed
Не пугайся, это второй аккаунт :) это все тот же ревьювер Александра

2023-02-02 19:30 UTC, ABashkirova commented on ImageFeed/SplashViewController.swift
>          }
Функция делает не то, что в ее описании. Это путает; 

Плюс все еще при завершении работы по получению токена-фетча, вместо сплеш скрина снова показывается экран авторизации. 
Это происходит, потому что viewDidAppear отрабатывает лишний раз, когда ты делаешь switchToTabBarController. 

Поэтому давай сделаем две вещи: 
1) назовем ее соответствующе. Тут обычно используют routeToAuth/TabBar или navigateTo, или showAuth – как нравится. 
2) не будем ничего вызывать на didAppear здесь. Но в viewDidLoad перепишем, вместо текущего кода вызовем функцию со следующим содержимым (я предлагаю проверку и навигацию определить в один метод)

```
if  oauth2TokenStorage.token == nil {
  showAuth() 
} else {
  fetchProfile()
}
```

2023-02-02 19:30 UTC, ABashkirova commented on ImageFeed/SplashViewController.swift
>                  break
здесь уже можно показывать алерт, раз он у тебя внизу реализован. Но в таком случае лучше UIBlockingProgressHUD.dismiss() вызвать до switch

2023-02-02 19:30 UTC, ABashkirova commented on ImageFeed/SplashViewController.swift
> +                break
break нужен, чтобы выходить из ветвления/цикла. В свитче его используют, когда не хотят обрабатывать кейс. Но так как у тебя уже есть код этом кейсе, брейк (или выход из кейса) произойдет по умолчанию. 

В этом случае он избыточен

2023-02-02 19:30 UTC, ABashkirova commented on ImageFeed/SplashViewController.swift
> +            UIBlockingProgressHUD.dismiss()
а почему понадобилось его тут скрывать?

2023-02-02 19:30 UTC, ABashkirova commented on ImageFeed/SplashViewController.swift
>  final class SplashViewController: UIViewController {
В этом классе все стало намного чище. Но есть странные промигивания AuthVC между переключением на таббар – надо исправить.

2023-02-02 19:30 UTC, ABashkirova commented on ImageFeed/TabBarController.swift
> +        profileViewController.tabBarItem = UITabBarItem(title: NSLocalizedString("Profile", comment: ""), image: UIImage(named: "tab_profile_active"), selectedImage: nil)
обрати внимание, что по дизайну никаких подписей вроде Profile не требуется у табов

2023-02-02 19:30 UTC, ABashkirova commented on ImageFeed/ProfileViewController.swift
> +import Kingfisher
Как будет время, удели этому классу внимание:

1) у аватара пользователя нет скругления, как в макете
2) цвет иконки не по макету на сколько я вижу
3) цвет фона стал черным. 
4) по коду можно убрать лишние комментарии в виде шагов


<img width="487" alt="Снимок экрана 2023-02-02 в 21 10 29" src="https://user-images.githubusercontent.com/20269264/216426979-baff7599-fda8-4150-9212-1b06cb7b551b.png">

2023-02-02 19:30 UTC, ABashkirova commented on ImageFeed/ProfileService.swift
> +        }
@flukekoh все-таки, возможно, авторы предлагают именно такой подход и ты прав. 

Но тогда получается, что такой подход подразумевает очередность запроса профиля и из двух мест одновременно попросить профиль не получится(по задаче и не надо, даже скорее нельзя). Для нашего проекта это верно. 

Снимаю свое предложение. Извини, если только запутала

2023-02-02 19:30 UTC, ABashkirova commented on ImageFeed/ProfileService.swift
> +        }
Возможно получится упростить этот код, если токен будет получатся сервисом из хранилища, а не передаваться внутрь функции:
```swift
guard lastToken != token {
   return
}
task?.cancel()
task = nil
```

определять свежесть /правильность токена не задача сервиса.

2023-02-02 19:30 UTC, ABashkirova commented on ImageFeed/ProfileService.swift
> +                }
я так и не поняла, все комплишены или только этот будет переданы на главную очередь?

2023-02-02 19:30 UTC, ABashkirova commented on ImageFeed/ProfileService.swift
> +                self?.lastToken = ""
Можно не хранить токен в этом сервисе, так как эта общий ключ на любые запросы в приложении, и он не должен просто так меняться от запроса к запросу.

2023-02-02 19:30 UTC, ABashkirova commented on ImageFeed/OAuth2/OAuth2TokenStorage.swift
> +            guard isSuccess else { return }
Можно проще через
 ```
if let newValue {
  KeychainWrapper.standard.set(newValue, forKey: "Auth token")
} else {
  KeychainWrapper.standard.removeObject(forKey: "Auth token")
 }

```
конструкция guard придумана для того чтобы писать gold-path, то есть отсекать неверные случае.

2023-02-03 10:10 UTC, flukekoh commented on ImageFeed/SplashViewController.swift
>          }
@ABashkirova не получается так сделать переместив в didload. Ошибка - Attempt to present on whose view is not in the window hierarchy https://stackoverflow.com/questions/11862883/attempt-to-present-uiviewcontroller-on-uiviewcontroller-whose-view-is-not-in-the

2023-02-03 10:12 UTC, flukekoh commented on ImageFeed/SplashViewController.swift
>                  break
Исправил

2023-02-03 10:12 UTC, flukekoh commented on ImageFeed/SplashViewController.swift
> +                break
Исправил

2023-02-03 10:21 UTC, flukekoh commented on ImageFeed/SplashViewController.swift
> +            UIBlockingProgressHUD.dismiss()
Лишнее. Убрал

2023-02-03 10:25 UTC, flukekoh commented on ImageFeed/TabBarController.swift
> +        profileViewController.tabBarItem = UITabBarItem(title: NSLocalizedString("Profile", comment: ""), image: UIImage(named: "tab_profile_active"), selectedImage: nil)
В учебнике и на учебных скринах именно с подписью

2023-02-03 10:28 UTC, flukekoh commented on ImageFeed/ProfileService.swift
> +                self?.lastToken = ""
Убрал

2023-02-03 10:29 UTC, flukekoh commented on ImageFeed/OAuth2/OAuth2TokenStorage.swift
> +            guard isSuccess else { return }
Исправил)

2023-02-03 10:36 UTC, flukekoh commented on ImageFeed/ProfileService.swift
> +                }
Это лишняя передача в очередь. Убрал

2023-02-03 10:46 UTC, ABashkirova commented on ImageFeed/TabBarController.swift
> +        profileViewController.tabBarItem = UITabBarItem(title: NSLocalizedString("Profile", comment: ""), image: UIImage(named: "tab_profile_active"), selectedImage: nil)
Спасибо за внимательность, отправлю коллегам исправлять!

2023-02-03 10:47 UTC, ABashkirova commented on ImageFeed/SplashViewController.swift
>          }
чорт, ладно, остаемся жить с таким поведением. У меня нет быстрого решения на эту тему. Но может у Наставников будет :)

2023-02-03 10:52 UTC, flukekoh commented on ImageFeed/SplashViewController.swift
>  final class SplashViewController: UIViewController {
Помигивания не знаю как исправить пока. Перенести в didload не сработало

2023-02-03 11:02 UTC, ABashkirova commented on ImageFeed/SplashViewController.swift
>  final class SplashViewController: UIViewController {
я себе помечу, сдавай как есть. Если придумаю что-то, передам тебе :)

2023-02-03 12:10 UTC, flukekoh commented on ImageFeed/SplashViewController.swift
>  final class SplashViewController: UIViewController {
Спасибо большое. Самому очень интересно

2023-02-03 17:34 UTC, IBDesignable reviewed
Как можно было бы решить эту проблему с рут контроллером:

можно попробовать презентоваться на навигейшен стеке, и менять рут контроллер у навстека(не виндоу) после того как таббар появится:
SplashVC -> TabBar [List, Profile] - собираем цепочку первым шагом,
вторым шагом оставляем TabBar [List, Profile]. 

Но это тоже само по себе нелегко: надо будет и убирать навбары, вовремя выталкивать лишний рут, затем предусмотреть на разлогин замену рута. 

Аналогичную затею можно поделать собирая флоу на разных widnow(у меня на проекте как раз SplashScreen является верхним окном, пока под ним второе окно инициализируется нужным вью контроллером). В момент перехода просто плавно fade-анимацией он исчезает :)

Эти приколы UIKit'а в продакшен приложениях обычно решают один раз и каждая команда делает это по своему, а потом переиспользуют во всем приложении. Предлагаю на этом этапе забить и поковыряться когда будет время самостоятельно. 
Полезно знать про эти подводные камни, но в больших проектах вряд ли поттребуется свой велосипед писать.

В этом проекте авторы пытаются пройти прямым путем, чтобы не забивать голову нетривиальными штуками, но как видишь не наступать на грабли сложно. 

--- 

Смотри, что осталось, но не в рамках этого ревью. Тебе надо с этим разобраться самостоятельно:
1. цвет фона на некоторых экранах, которые ты верстаешь кодом – черный, это не ок
2. у профиля все таки надо убрать лейбл в табе, чтобы быть в макетах
3. градиент в ячейке реализован неверно. рекомендую от него отказаться. Неверно это значит что он показывается не на всей длине ячейки с высотой 30 и наслаивается каждый раз при конфигурации ячейки. от чего белая подложка получается (см скрин)
4. Вернуться к комментариям по профилю 
 
<img width="487" alt="Снимок экрана 2023-02-03 в 19 18 05" src="https://user-images.githubusercontent.com/121577115/216666313-cbfc514b-8bc9-4437-aa4d-ad3d81531bb7.png">

Это все надо сделать до сдачи следующего спринта. иначе проверка и замечания посыпятся вторым кругом.

2023-02-03 17:34 UTC, IBDesignable commented on ImageFeed/ProfileViewController.swift
>      override func viewDidLoad() {
не забывай вызывать super.viewDidLoad

2023-02-06 16:26 UTC, merged